server:
  port: 30080
spring:
  application:
    name: vortex-tsd-service
  profiles:
    active: local
  freemarker:
    cache: false
    charset: UTF-8
    enabled: true
    expose-request-attributes: true
    expose-session-attributes: true
    setting:
      number_format: '#'
      url_escaping_charset: UTF-8
    suffix: .ftl
    template-loader-path: classpath:/META-INF/templates/
    


    
