spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456

doodler:
  transmitter:
    nio:
      server:
        bindHostName: 192.168.159.1
    event:
      logging:
        enabled: true